apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: let-me-encrypt-prod
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: "rowin@derow.nl"
    privateKeySecretRef:
      name: let-me-encrypt-prod
    solvers:
      - http01:
          ingress:
            class: nginx
