name: Frontend unit tests

on: [push]

jobs:
  unit-test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build dockerfile
      run: docker build -t rowin1125/react-test -f ./client/Dockerfile.dev ./client
    - name: Run tests
      run: docker run -e CI=true rowin1125/react-test npm test
