name: Deploy React app to GKE

on:
  push:
    branches:
    - main

env:
  PROJECT_ID: ${{ secrets.GKE_PROJECT }}
  GKE_CLUSTER: multi-cluster    # TODO: update to cluster name
  GKE_ZONE: europe-west4-a	   # TODO: update to cluster zone
  # DEPLOYMENT_NAME: gke-hello-app # TODO: update deployment name if changed in deployment.yaml

jobs:
  unit-test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: build dockerfile
      run: docker build -t rowin1125/react-test -f ./client/Dockerfile.dev ./client
    - name: Run tests
      run: docker run -e CI=true rowin1125/react-test npm test

  setup-and-deploy:
    name: Setup and Deploy
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    # Setup gcloud CLI
    - uses: google-github-actions/setup-gcloud@master
      with:
        service_account_key: ${{ secrets.GKE_SA_KEY }}
        project_id: ${{ secrets.GKE_PROJECT }}

    # Get the GKE credentials so we can deploy to the cluster
    - run: |-
        gcloud container clusters get-credentials "$GKE_CLUSTER" --zone "$GKE_ZONE"
    # Deploy sample image to the GKE cluster
    - name: Deploy
      run: |-
        kubectl apply -f k8s/
        kubectl get services -o wide
